minimum_pre_commit_version: 2.10.0
exclude: '^.idea'
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3298ddab3c13dd77d6ce1fc0baf97691430d84b0  # frozen: v4.3.0
    hooks:
      - id: fix-byte-order-marker
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: check-vcs-permalinks
      - id: debug-statements
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
  - repo: https://github.com/Yelp/detect-secrets.git
    rev: 4d855d36b48af9b90156971bc6ff18e91c0fa677  # frozen: v1.3.0
    hooks:
      - id: detect-secrets
        #        args: ['--baseline', '.secrets.baseline']
        exclude: "(Cargo.lock)|(.pre-commit-config.yaml)"
  - repo: https://github.com/AleksaC/hadolint-py
    rev: ecf2d2c004e7a753f48e44952a81d7c9cf1f202c  # frozen: v2.10.0
    hooks:
      - id: hadolint
